CREATE TABLE media (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  filename TEXT NOT NULL,
  key TEXT NOT NULL,
  url TEXT NOT NULL,
  contentType TEXT NOT NULL,
  size INTEGER NOT NULL DEFAULT 0,
  alt TEXT,
  uploadedBy INTEGER NOT NULL REFERENCES users(id),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
