CREATE TABLE entries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  contentTypeId INTEGER NOT NULL REFERENCES content_types(id),
  slug TEXT NOT NULL,
  data TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'draft',
  authorId INTEGER NOT NULL REFERENCES users(id),
  publishedAt DATETIME,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(contentTypeId, slug)
);
