CREATE TABLE api_keys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  key TEXT UNIQUE NOT NULL,
  permissions TEXT NOT NULL DEFAULT '[]',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  lastUsedAt DATETIME
);
