CREATE TABLE revisions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  entryId INTEGER NOT NULL REFERENCES entries(id),
  data TEXT NOT NULL,
  authorId INTEGER NOT NULL REFERENCES users(id),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
