export type { CommandDef, FlagDef, ParsedArgs } from "./command/index.ts";
export { cli, command, flag, parseArgs } from "./command/index.ts";
export type { ProcSpec } from "./foreman/index.ts";
export { foreman, parseProcfile } from "./foreman/index.ts";
export { initCommand } from "./init/index.ts";
export { addCommand } from "./add/index.ts";
export { docsCommand } from "./docs/index.ts";
export { questions, applyDefaults, getQuestionSpec } from "./init/questions.ts";
export type { Question, Answers } from "./init/questions.ts";
export { generateProject } from "./init/templates.ts";
